apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::0579618009402:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EE18UG2IEXXG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::0579618009402:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-24T21:17:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1726"
  uid: 1d09859c-66b0-41bc-8d05-38547d63733f
